### ISSUE TITLE
getAddress() returns old key

### ISSUE THREAD

**Issue by yapyuyou** [rjchow/ethers-aws-kms-signer#9]
While implementing key rotation it was found that `getAddress()` does not return us the latest value but the signer still signs using the latest one. This mismatch in addresses is causing the signed docs to be invalid.

https://github.com/rjchow/ethers-aws-kms-signer/blob/8e3a4812b542e86ac9d3b6da02b794eb1b5be86d/src/index.ts#L23 

Can we add an optional param to skip the if statement above?

**Comment by rjchow** [comment]
You should probably be creating a new signer with a new keyid after rotating keys

**Comment by yehjxraymond** [comment]
Use a proxy as a permanent identity.

EOA (can be rotated) --> Identity Proxy --> Other smart contracts

*I'm assuming on-chain interaction here.

**Comment by yapyuyou** [comment]
We are not using the keyids but rather an alias that the new key takes over. Right now the behaviour is that `getAddress` will still return the old one but the new key will be used when signing.

The signer is only ever instantiated once so isn't the expected behaviour that the returned value from `getAddress` is consistent with the key used to sign when calling `signMessage`?

**Comment by rjchow** [comment]
None of that is the concern of this library - the library instantiates a Ethers Signer given a set of AWS credentials + KMS Key ID, and expects that the Key ID should not change out from under it. 

You should be instantiating a new Signer whenever you expect to use a different KMS Key.
